markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: "Trees"
markdown: rdiscount

author: "小树"
atom-baseurl: "http://xushucan.cn"

navigations:
  - title: 文章
    class: fa fa-list-ul
    href: /archive.html
  - title: 标签
    class: fa fa-tags
    href: /tags.html
  - title: 关于
    class: fa fa-user
    href: /about.html
  - title: 相册
    class: fa fa-film
    href: javascript:alert('待推出')
  - title: 收藏
    class: fa fa-link
    href: /links.html
  - title: 订阅
    class: fa fa-rss
    href: /atom.xml

